export const organiserConfig = {
  organisers: [
    {
      id: 1,
      name: "Himanshu Kumar Sahu",
      title: "Organizing Lead",
      image: "/images/organisers/Himanshu-min.jpg",
      imagePosition: "center",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/HimanshuKS10",
      linkedin: "https://www.linkedin.com/in/himanshuks0110",
    },
    {
      id: 2,
      name: "Ayush Kumar Sahu",
      title: "Operations & PR Lead",
      image: "/images/organisers/Ayush-min.jpg",
      imagePosition: "center",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/Ayush_7477",
      linkedin: "https://www.linkedin.com/in/ayushsahu77/",
    },
    {
      id: 3,
      name: "Fanibhushan Sahu",
      title: "Graphic Lead",
      image: "/images/organisers/Fani-min.jpg",
      imagePosition: "top",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/fani_sahu",
      linkedin: "https://www.linkedin.com/in/fanibhushan-sahu-347697234",
    },
    {
      id: 4,
      name: "Vinitpal Singh",
      title: "Technical Lead",
      image: "/images/organisers/vinit-min.jpg",
      imagePosition: "top",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/vinitpal_arora",
      linkedin: "https://www.linkedin.com/in/vinitpal-singh",
    },
    {
      id: 5,
      name: "Akash Kumar Verma",
      title: "Technical Lead",
      image: "/images/organisers/Akash-min.jpg",
      imagePosition: "center",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/Nerdon36",
      linkedin: "https://www.linkedin.com/in/akashverma095",
    },
    {
      id: 6,
      name: "Anshumaan Kumar Prasad",
      title: "GitHub support",
      image: "/images/organisers/Aminos-min.jpeg",
      imagePosition: "center",
      alt: "Hack the space Hackathon Organisers",
      twitter: "https://twitter.com/aminoxix",
      linkedin: "https://www.linkedin.com/in/aminoxix",
    },
  ],
  coreTeam: [
    {
      href: "#",
      name: "Akshat Sahu",
      title: "Graphics Team",
      image: "/images/CoreTeam/Akshat Sahu.jpg",
    },
    {
      href: "https://www.linkedin.com/in/anubhav-choubey-653680150/",
      name: "Anubhav Choubey",
      title: "PR & Social Media Team",
      image: "/images/CoreTeam/anubhav choubey.png",
    },
    {
      href: "https://www.linkedin.com/in/ashutosh-kashyap-8600a6240",
      name: "Ashutosh Kashyap",
      title: "PR & Social Media Team",
      image: "/images/CoreTeam/Ashutosh_Kashyap.jpg",
    },
    {
      href: "https://www.linkedin.com/in/harshgupta-in/",
      name: "Harsh Gupta",
      title: "Tech Team",
      image: "/images/CoreTeam/Harsh Gupta.jpg",
    },
    {
      href: "https://www.linkedin.com/in/lomesh-patil-b519a21b3",
      name: "Lomesh Patil",
      title: "PR & Social Media Team",
      image: "/images/CoreTeam/Lomesh Patil.jpg",
    },
    {
      href: "https://www.linkedin.com/in/mohit-makda-608849221",
      name: "Mohit Makda",
      title: "Tech Team",
      image: "/images/CoreTeam/mohit.jpg",
    },
    {
      href: "https://www.linkedin.com/in/prashansa-purohit-a9a786239",
      name: "Prashansa Purohit",
      title: "PR & Social Media",
      image: "/images/CoreTeam/Prashansa  - Prashansa Purohit.jpg",
    },
    {
      href: "https://www.linkedin.com/in/shubham-jha-58b7b0281",
      name: "Shubham Jha",
      title: "Graphics Team",
      image: "/images/CoreTeam/Shubham Jha.jpg",
    },
    {
      href: "https://www.linkedin.com/in/shweta-cheemalapati-0082b8237",
      name: "Shweta Cheemalapati",
      title: "Content Team",
      image: "/images/CoreTeam/Shweta C.jpg",
    },
    {
      href: "https://www.linkedin.com/in/siddharth-sahu-10/",
      name: "Siddharth Sahu",
      title: "Tech Team",
      image: "/images/CoreTeam/Siddharth - Siddharth Sahu.jpg",
    },
    {
      href: "https://www.linkedin.com/in/smit-javia-824221239",
      name: "Smit Javia",
      title: "Graphics Team",
      image: "/images/CoreTeam/Smit Javia.jpg",
    },
    {
      href: "https://www.linkedin.com/in/darshita-ahuja-9a448b225",
      name: "Darshita Ahuja",
      title: "Content Team",
      image: "/images/CoreTeam/darshita.png",
    },
    {
      href: "https://www.linkedin.com/in/gaurav-chandrakar-86431a226",
      name: "Gaurav Chandrakar",
      title: "Graphics Team",
      image: "/images/CoreTeam/gaurav.jpg",
    },
    {
      href: "https://www.linkedin.com/in/apeksha-vaishnaw-56533726a",
      name: "Apeksha Vaishnav",
      title: "Logistics Team",
      image: "/images/CoreTeam/apeksha.jpg",
    },
    {
      href: "https://www.linkedin.com/in/anaytripathy",
      name: "Anay Tripathy",
      title: "Logistics Team",
      image: "/images/CoreTeam/anay.jpeg",
    },
  ],
};
