export const SpeakerConfig = [
  {
    id: 1,
    linkedin: "https://www.linkedin.com/in/jaysaadana/",
    twitter: "https://twitter.com/jaysaadana",
    name: "Jay Saadana",
    title: "Lead Ambassador | Quine",
    image: "/images/Speakers/Jay Saadana.jpeg",
  },
  {
    linkedin: "#",
    twitter: "https://twitter.com/Frenzyritz13",
    id: 2,
    name: "Ritvi Mishra",
    title: "Developer Advocate | Dyte",
    image: "/images/Speakers/Ritvi Mishra.jpeg",
  },
  {
    id: 3,
    linkedin: "https://www.linkedin.com/in/abhishekdoshi26/",
    twitter: "https://twitter.com/AbhishekDoshi26",
    name: "Abhishek Doshi",
    title: "Google Developer Expert",
    image: "/images/Speakers/Abhishek Doshi.jpeg",
  },
  {
    id: 4,
    linkedin: "https://www.linkedin.com/in/the-khushi-trivedi/",
    twitter: "https://twitter.com/KhushiT113",
    name: "Khushi Trivedi",
    title: "Gold MLSA",
    image: "/images/Speakers/Khushi Trivedi.jpeg",
  },
  {
    id: 5,
    linkedin: "https://www.linkedin.com/in/kuldeep-pisda/",
    twitter: "https://twitter.com/kdpisda",
    name: "Kuldeep Pisda",
    title: "Building PeekLink | Organizer @GDGRaipur",
    image: "/images/Speakers/Kudeep Pisda.jpg",
  },
  {
    id: 6,
    linkedin: "https://www.linkedin.com/in/theimpulson/",
    twitter: "#",
    name: "Aayush Gupta",
    title: "Android Developer",
    image: "/images/Speakers/Aayush Gupta.jpeg",
  },
  {
    id: 7,
    linkedin: "https://www.linkedin.com/in/mdmemonyasin/",
    twitter: "https://twitter.com/mdmemonyasin",
    name: "Mohammad Yasin",
    title: "Software Engineer @boardinfinity",
    image: "/images/Speakers/Mohammad Yasin.jpeg",
  },
  {
    id: 8,
    linkedin: "https://www.linkedin.com/in/niketjain8/",
    twitter: "https://twitter.com/nikeight_",
    name: "Niket Jain",
    title: "Android Developer @Mutual Mobile",
    image: "/images/Speakers/Niket Jain.jpg",
  },
  {
    id: 9,
    linkedin: "https://www.linkedin.com/in/pranjal-tiwari-08346919a/",
    twitter: "https://twitter.com/impranjaljs",
    name: "Pranjal Tiwari",
    title: "Software Developer @Impulsive Web",
    image: "/images/Speakers/Pranjal Tiwari.jpeg",
  },
  {
    id: 10,
    linkedin: "https://www.linkedin.com/in/aayushbisen/",
    twitter: "https://twitter.com/aayushbisen_",
    name: "Aayush Bisen",
    title: "Software Engineer @Health Vectors",
    image: "/images/Speakers/Aayush Bisen.jpeg",
  },
  {
    id: 11,
    linkedin: "https://www.linkedin.com/in/paramsiddharth/",
    twitter: "https://twitter.com/ParamSiddharth",
    name: "Param Siddharth",
    title: "SDE @TravelopiaGroup",
    image: "/images/Speakers/Param Siddharth.jpeg",
  },
];
